=== axkrap/community-cms/communitycms/docs/permission_list.dtd
<?xml version='1.0' encoding='UTF-8'?>

<!ELEMENT permission_list (category+)>

<!ELEMENT category (key?,key_range?)>
<!ATTLIST category
    name CDATA #REQUIRED
>

<!ELEMENT key EMPTY>
<!ATTLIST key
    name CDATA #REQUIRED
	title CDATA #REQUIRED
	description CDATA #REQUIRED
	default CDATA #IMPLIED
>

<!ELEMENT key_range EMPTY>
<!ATTLIST key_range
	regex CDATA #REQUIRED
>

=== axkrap/community-cms/includes/acl/permission_list.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE permission_list SYSTEM "../../docs/permission_list.dtd">
<permission_list>
	<category name="General">
		<key name="all"
			 title="All Permissions"
			 description="Grant this permission to allow all actions within the CMS" />
		<key name="admin_access"
			 title="Admin Access"
			 description="Allow a user to access the administrative section of the CMS" />
		<key name="set_permissions"
			 title="Set Permissions"
			 description="Allow a user to modify the permission settings for user groups" />
		<key name="show_editbar"
			 title="Show Editbar"
			 description="Allow a user to see the edit bar on front-end content" />
		<key name="show_fe_errors"
			 title="Show Front-End Errors"
			 description="Allow a user to view error messages in the CMS front-end that would normally be hidden from users" />
		<key name="log_post_custom_message"
			 title="Post Custom Log Messages"
			 description="Allow a user to post custom log messages" />
		<key name="adm_help"
			 title="Admin Help Module"
			 description="Allow a user to access the help module" />
		<key name="adm_feedback"
			 title="Admin Feedback Module"
			 description="Allow a user to access the admin feedback module" />
	</category>
	<category name="Maintentance/Settings">
		<key name="adm_site_config"
			 title="Site Configuration"
			 description="Allow a user to modify the CMS configuration" />
		<key name="adm_gallery_settings"
			 title="Gallery Settings"
			 description="Allow a user to configure image galleries" />
		<key name="adm_news_settings"
			 title="News Settings"
			 description="Allow a user to configure news settings" />
		<key name="calendar_settings"
			 title="Calendar Settings"
			 description="Allow a user to modify calendar settings" />
		<key name="adm_log_view"
			 title="View Logs"
			 description="Allow a user to access the admin activity logs" />
		<key name="log_clear"
			 title="Clear Logs"
			 description="Allow a user to clear all log messages" />
		<key name="adm_config_view"
			 title="View Configuration"
			 description="Allow a user to view all of the CMS configuration values" />
	</category>
	<category name="Blocks">
		<key name="adm_block_manager"
			 title="Block Module"
			 description="Allow a user to access the block manager module" />
		<key name="block_create"
			 title="Create Blocks"
			 description="Allow a user to create new blocks" />
		<key name="block_delete"
			 title="Delete Blocks"
			 description="Allow a user to delete blocks" />
		<key name="block_edit"
			 title="Edit Blocks"
			 description="Allow a user to edit blocks" />
	</category>
	<category name="Calendar">
		<key name="adm_calendar"
			 title="Calendar Module"
			 description="Allow a user to access the calendar manager module" />
		<key name="date_create"
			 title="Create Events"
			 description="Allow a user to create calendar event entries" />
		<key name="adm_calendar_edit_date"
			 title="Calendar Edit"
			 description="Allow a user to access the calendar edit module" />
		<key name="adm_calendar_locations"
			 title="Manage Locations"
			 description="Allow a user to manage calendar locations" />
	</category>
	<category name="Contacts">
		<key name="adm_contacts_manage"
			 title="Contacts Module"
			 description="Allow a user to access the contacts manager module" />
		<key name="contacts_edit_lists"
			 title="Edit Contact Lists"
			 description="Allow a user to change the entries on contact lists" />
		<key name="contacts_create"
			 title="Create Contacts"
			 description="Allow a user to create contact records" />
		<key name="contacts_edit"
			 title="Edit Contacts"
			 description="Allow a user to edit contact records" />
		<key name="contacts_delete"
			 title="Delete Contacts"
			 description="Allow a user to delete contact records" />
	</category>
	<category name="Files">
		<key name="adm_filemanager"
			 title="File Manager"
			 description="Allow a user to access the file manager module" />
		<key name="file_create_folder"
			 title="Create Folders"
			 description="Allow a user to create new folders" />
		<key name="file_upload"
			 title="Upload Files"
			 description="Allow a user to upload files" />
		<key name="file_delete"
			 title="Delete Files"
			 description="Allow a user to delete uploaded files" />
	</category>
	<category name="Image Galleries">
		<key name="adm_gallery_manager"
			 title="Gallery Manager"
			 description="Allow a user to access the gallery manager module" />
	</category>
	<category name="News">
		<key name="adm_news"
			 title="News Module"
			 description="Allow a user to access the news article module" />
		<key name="news_create"
			 title="Create Articles"
			 description="Allow a user to create new news articles" />
		<key name="news_delete"
			 title="Delete Articles"
			 description="Allow a user to delete news articles" />
		<key name="news_edit"
			 title="Edit Articles"
			 description="Allow a user to edit news articles" />
		<key name="news_publish"
			 title="Publish/Unpublish Articles"
			 description="Allow a user to publish or unpublish news articles" />
		<key name="news_fe_show_unpublished"
			 title="Show Unpublished News on Site"
			 description="Allow a user to see unpublished articles from the site front-end" />
	</category>
	<category name="Newsletters">
		<key name="adm_newsletter"
			 title="Newsletter Module"
			 description="Allow a user to access the newsletter module" />
		<key name="newsletter_create"
			 title="Create Newsletter"
			 description="Allow a user to create a new newsletter" />
		<key name="newsletter_delete"
			 title="Delete Newsletter"
			 description="Allow a user to delete a newsletter" />
	</category>
	<category name="Pages">
		<key name="adm_page"
			 title="Page Module"
			 description="Allow a user to access the page manager module" />
		<key name="page_set_home"
			 title="Change Default Page"
			 description="Allow a user to change the defualt CMS page" />
		<key name="page_order"
			 title="Change Page Order"
			 description="Allow a user to rearrange pages on the CMS menu" />
		<key name="page_create"
			 title="Create Pages"
			 description="Allow a user to create new pages" />
		<key name="page_delete"
			 title="Delete Pages"
			 description="Allow a user to delete pages" />
		<key name="page_edit"
			 title="Edit Pages"
			 description="Allow a user to edit pages (requires ability to edit specific page groups)" />
		<key name="page_group_create"
			 title="Create Page Groups"
			 description="Allow a user to create new page groups" />
		<key_range regex="/^pagegroupedit\-/i" />
	</category>
	<category name="Page Messages">
		<key name="adm_page_message"
			 title="Page Message Module"
			 description="Allow a user to access the page message module" />
		<key name="adm_page_message_edit"
			 title="Edit Page Messages"
			 description="Allow a user to edit page messages" />
		<key name="page_message_new"
			 title="Create Page Messages"
			 description="Allow a user to create new page messages" />
		<key name="page_message_delete"
			 title="Delete Page Messages"
			 description="Allow a user to delete existing page messages" />
	</category>
	<category name="Polls">
		<key name="adm_poll_manager"
			 title="Poll Manager Module"
			 description="Allow a user to access the poll manager module" />
		<key name="poll_create"
			 title="Create Polls"
			 description="Allow a user to create new polls" />
		<key name="adm_poll_results"
			 title="Poll Results"
			 description="Allow a user to see the results of polls" />
	</category>
	<category name="Users and Groups">
		<key name="adm_user"
			 title="User Module"
			 description="Allow a user to access the user manager module" />
		<key name="adm_user_edit"
			 title="Edit User Module"
			 description="Allow a user to access the edit user module" />
		<key name="adm_user_groups"
			 title="User Groups Module"
			 description="Allow a user to access the user groups module" />
		<key name="user_create"
			 title="Create User"
			 description="Allow a user to create new users" />
		<key name="user_delete"
			 title="Delete User"
			 description="Allow a user to delete other users" />
		<key name="group_create"
			 title="Create User Groups"
			 description="Allow a user to create a new user group" />
	</category>
</permission_list>
