=== axkrap/community-cms/docs/acl.dtd
<?xml version='1.0' encoding='UTF-8'?>

<!ELEMENT propertylist (category+)>

<!ELEMENT category (item+)>
<!ATTLIST category
    name CDATA #REQUIRED
  >

<!ELEMENT item EMPTY>
<!ATTLIST item
    label CDATA #IMPLIED
    name CDATA #REQUIRED
  >

=== axkrap/community-cms/includes/acl.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE propertylist SYSTEM "../docs/acl.dtd">
<propertylist>
	<category name="Uncategorized">
		<item name="all" label="All Permissions"></item>
		<item name="admin_access" label="Administration Backend Access"></item>
		<item name="adm_block_manager"></item>
		<item name="adm_calendar"></item>
		<item name="adm_calendar_edit_date"></item>
		<item name="adm_calendar_settings"></item>
		<item name="adm_feedback"></item>
		<item name="adm_filemanager"></item>
		<item name="adm_help"></item>
		<item name="adm_index"></item>
		<item name="adm_log_view"></item>
		<item name="adm_news"></item>
		<item name="adm_news_edit_article"></item>
		<item name="adm_news_settings"></item>
		<item name="adm_newsletter"></item>
		<item name="adm_page_message"></item>
		<item name="adm_page_message_edit"></item>
		<item name="adm_page_message_new"></item>
		<item name="adm_poll_manager"></item>
		<item name="adm_poll_new"></item>
		<item name="adm_poll_results"></item>
		<item name="adm_site_config"></item>
		<item name="adm_upload_mini"></item>
		<item name="adm_user"></item>
		<item name="adm_user_create"></item>
		<item name="adm_user_edit"></item>
		<item name="adm_user_groups"></item>
		<item name="adm_user_permission"></item>
		<item name="log_clear"></item>
		<item name="log_post_custom_message"></item>
		<item name="set_permissions"></item>
	</category>
	<category name="Pages">
		<item name="adm_page" label="Access page manager"></item>
		<item name="page_delete" label="Delete pages"></item>
		<item name="page_set_home" label="Change home page"></item>
	</category>
</propertylist>
