=== axkrap/community-cms/docs/blocks.dtd
<?xml version='1.0' encoding='UTF-8'?>

<!ELEMENT blocklist (block)*>

<!ELEMENT block (name,attribute*)>

<!ELEMENT name (#PCDATA)>

<!ELEMENT attribute (attbname,label,type,values?)>

<!ELEMENT attbname (#PCDATA)>

<!ELEMENT label (#PCDATA)>

<!ELEMENT type (#PCDATA)>

<!ELEMENT values (value+)>

<!ELEMENT value (#PCDATA)>

=== axkrap/community-cms/includes/blocks.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE blocklist SYSTEM "../docs/blocks.dtd">
<blocklist>
	<block>
		<name>poll</name>
		<attribute>
			<attbname>question_id</attbname>
			<label>Question ID</label>
			<type>int</type>
		</attribute>
	</block>
	<block>
		<name>text</name>
		<attribute>
			<attbname>article_id</attbname>
			<label>Article ID</label>
			<type>int</type>
		</attribute>
	</block>
	<block>
		<name>events</name>
		<attribute>
			<attbname>mode</attbname>
			<label>Display Mode</label>
			<type>option</type>
			<values>
				<value>upcoming</value>
				<value>past</value>
			</values>
		</attribute>
		<attribute>
			<attbname>num</attbname>
			<label>Number of Entries</label>
			<type>int</type>
		</attribute>
	</block>
	<block>
		<name>calendarcategories</name>
	</block>
</blocklist>
